# Render configuration for backend deployment

services:
  - type: web
    name: image-upload-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    
    # Environment variables (set these in Render dashboard)
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      # Add these in Render dashboard:
      # - AWS_ACCESS_KEY_ID
      # - AWS_SECRET_ACCESS_KEY  
      # - AWS_REGION
      # - S3_BUCKET_NAME
      # - FRONTEND_URL

# Alternative: Static site for frontend (if deploying both)
# - type: web
#   name: image-upload-frontend
#   env: static
#   buildCommand: npm install && npm run build
#   staticPublishPath: ./build
#   routes:
#     - type: rewrite
#       source: /*
#       destination: /index.html